# Generated by Django 5.2.11 on 2026-02-22 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0002_alter_company_options_joinrequest'),
        ('products', '0002_alter_product_options_alter_supply_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_name', models.CharField(max_length=255, verbose_name='Имя покупателя')),
                ('sale_date', models.DateTimeField(verbose_name='Дата продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='companies.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'db_table': 'sales_sale',
                'ordering': ('-sale_date',),
            },
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price_at_sale', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена на момент продажи')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='products.product', verbose_name='Товар')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_sales', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Товар в продаже',
                'verbose_name_plural': 'Товары в продаже',
                'db_table': 'sales_product_sale',
                'constraints': [models.UniqueConstraint(fields=('sale', 'product'), name='unique_sale_product')],
            },
        ),
    ]
