# Generated by Django 5.2.11 on 2026-02-22 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsale',
            name='price_at_sale',
        ),
    ]
