# Generated by Django 5.2.11 on 2026-02-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ('-delivery_date',), 'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AddConstraint(
            model_name='supplyproduct',
            constraint=models.UniqueConstraint(fields=('supply', 'product'), name='unique_supply_product'),
        ),
    ]
